---
# jenkins_plugin module doesn't support password files.
- name: Get Jenkins admin password from file.
  slurp:
    src: "{{ jenkins_admin_password_file }}"
  register: adminpasswordfile
  no_log: true
  when: jenkins_admin_password_file != ""
  tags: ['skip_ansible_lint']

- name: Set Jenkins admin password fact.
  set_fact:
    jenkins_admin_password: "{{ adminpasswordfile['stdout'] | default(jenkins_admin_password) }}"
  no_log: true

# Update Jenkins so that plugin updates don't fail.
- name: Create Jenkins updates directory.
  file:
    path: "{{ jenkins_home }}/updates"
    state: directory
    owner: jenkins
    group: jenkins

# Download plugin(s) for installation via jenkins-cli
- name: Download plugins
  get_url:
    url: "{{ jenkins_pkg_url }}/plugins/{{ item }}"
    dest: "/tmp/plugins/{{ item }}"
  loop: "{{ jenkins_plugins }}"
  when: (jenkins_plugins | length) > 0

# Install the plugins via jenkins-cli
- name: Install the plugins
  command:
    argv:
      - "java -jar {{ jenkins_jar_location }} -s http://127.0.0.1:{{ jenkins_http_port }}/{{ jenkins_url_prefix }}"
      - "install-plugin {{ item }}"
      - "--username admin --password {{ jenkins_admin_password }}"
  loop: "{{ jenkins_plugins }}"
  when: (jenkins_plugins | length) > 0